"""empty message

Revision ID: 025fcf81bc8c
Revises: dadc7c118e68
Create Date: 2024-12-04 19:12:02.365172

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "025fcf81bc8c"
down_revision: Union[str, None] = "dadc7c118e68"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("metric", schema=None) as batch_op:
        batch_op.create_unique_constraint("metric_ident", ["provider_id", "slug"])
        batch_op.drop_column("version")

    with op.batch_alter_table("metric_execution", schema=None) as batch_op:
        batch_op.create_unique_constraint("metric_execution_ident", ["metric_id", "key"])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("metric_execution", schema=None) as batch_op:
        batch_op.drop_constraint("metric_execution_ident", type_="unique")

    with op.batch_alter_table("metric", schema=None) as batch_op:
        batch_op.add_column(sa.Column("version", sa.VARCHAR(), nullable=False))
        batch_op.drop_constraint("metric_ident", type_="unique")

    # ### end Alembic commands ###
