"""metric-uc

Revision ID: 439dd6bc6cc6
Revises: 025fcf81bc8c
Create Date: 2024-12-05 08:48:33.252479

"""

from collections.abc import Sequence
from typing import Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "439dd6bc6cc6"
down_revision: Union[str, None] = "025fcf81bc8c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("metric_execution_result", schema=None) as batch_op:
        batch_op.drop_index("ix_metric_execution_result_dataset_hash")
        batch_op.create_index(
            batch_op.f("ix_metric_execution_result_dataset_hash"), ["dataset_hash"], unique=False
        )
        batch_op.create_unique_constraint(
            "metric_execution_result_ident", ["metric_execution_id", "dataset_hash"]
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("metric_execution_result", schema=None) as batch_op:
        batch_op.drop_constraint("metric_execution_result_ident", type_="unique")
        batch_op.drop_index(batch_op.f("ix_metric_execution_result_dataset_hash"))
        batch_op.create_index("ix_metric_execution_result_dataset_hash", ["dataset_hash"], unique=1)

    # ### end Alembic commands ###
