"""series-metric-value

Revision ID: dd3e2abd0836
Revises: 341a4aa2551e
Create Date: 2025-05-07 14:46:11.383655

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dd3e2abd0836"
down_revision: Union[str, None] = "341a4aa2551e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("metric_value", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("type", sa.Enum("SCALAR", "SERIES", name="metricvaluetype"), nullable=False)
        )
        batch_op.add_column(sa.Column("values", sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column("index", sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column("index_name", sa.String(), nullable=True))
        batch_op.alter_column("value", existing_type=sa.FLOAT(), nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("metric_value", schema=None) as batch_op:
        batch_op.alter_column("value", existing_type=sa.FLOAT(), nullable=False)
        batch_op.drop_column("index_name")
        batch_op.drop_column("index")
        batch_op.drop_column("values")
        batch_op.drop_column("type")

    # ### end Alembic commands ###
