"""add indexes

Revision ID: 8d28e5e0f9c3
Revises: ba5e
Create Date: 2025-09-05 20:19:18.311472

"""

from collections.abc import Sequence
from typing import Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8d28e5e0f9c3"
down_revision: Union[str, None] = "ba5e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("cmip6_dataset", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_cmip6_dataset_experiment_id"), ["experiment_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_cmip6_dataset_instance_id"), ["instance_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_cmip6_dataset_member_id"), ["member_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_cmip6_dataset_source_id"), ["source_id"], unique=False)

    with op.batch_alter_table("dataset", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_dataset_dataset_type"), ["dataset_type"], unique=False)

    with op.batch_alter_table("dataset_file", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_dataset_file_dataset_id"), ["dataset_id"], unique=False)

    with op.batch_alter_table("diagnostic", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_diagnostic_updated_at"), ["updated_at"], unique=False)

    with op.batch_alter_table("execution", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_execution_execution_group_id"), ["execution_group_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_execution_successful"), ["successful"], unique=False)
        batch_op.create_index(batch_op.f("ix_execution_updated_at"), ["updated_at"], unique=False)

    with op.batch_alter_table("execution_dataset", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_execution_dataset_dataset_id"), ["dataset_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_execution_dataset_execution_id"), ["execution_id"], unique=False)

    with op.batch_alter_table("execution_group", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_execution_group_diagnostic_id"), ["diagnostic_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_execution_group_updated_at"), ["updated_at"], unique=False)

    with op.batch_alter_table("execution_output", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_execution_output_updated_at"), ["updated_at"], unique=False)

    with op.batch_alter_table("metric_value", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_metric_value_execution_id"), ["execution_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_metric_value_type"), ["type"], unique=False)
        batch_op.create_index(batch_op.f("ix_metric_value_updated_at"), ["updated_at"], unique=False)

    with op.batch_alter_table("provider", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_provider_updated_at"), ["updated_at"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("provider", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_provider_updated_at"))

    with op.batch_alter_table("metric_value", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_metric_value_updated_at"))
        batch_op.drop_index(batch_op.f("ix_metric_value_type"))
        batch_op.drop_index(batch_op.f("ix_metric_value_execution_id"))

    with op.batch_alter_table("execution_output", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_execution_output_updated_at"))

    with op.batch_alter_table("execution_group", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_execution_group_updated_at"))
        batch_op.drop_index(batch_op.f("ix_execution_group_diagnostic_id"))

    with op.batch_alter_table("execution_dataset", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_execution_dataset_execution_id"))
        batch_op.drop_index(batch_op.f("ix_execution_dataset_dataset_id"))

    with op.batch_alter_table("execution", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_execution_updated_at"))
        batch_op.drop_index(batch_op.f("ix_execution_successful"))
        batch_op.drop_index(batch_op.f("ix_execution_execution_group_id"))

    with op.batch_alter_table("diagnostic", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_diagnostic_updated_at"))

    with op.batch_alter_table("dataset_file", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_dataset_file_dataset_id"))

    with op.batch_alter_table("dataset", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_dataset_dataset_type"))

    with op.batch_alter_table("cmip6_dataset", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_cmip6_dataset_source_id"))
        batch_op.drop_index(batch_op.f("ix_cmip6_dataset_member_id"))
        batch_op.drop_index(batch_op.f("ix_cmip6_dataset_instance_id"))
        batch_op.drop_index(batch_op.f("ix_cmip6_dataset_experiment_id"))

    # ### end Alembic commands ###
