"""use 'version' as version facet for obs4MIPs

Revision ID: 2f6e36738e06
Revises: 8d28e5e0f9c3
Create Date: 2025-09-10 13:58:40.660076

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2f6e36738e06"
down_revision: Union[str, None] = "8d28e5e0f9c3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("obs4mips_dataset", schema=None) as batch_op:
        batch_op.add_column(sa.Column("version", sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("obs4mips_dataset", schema=None) as batch_op:
        batch_op.drop_column("version")

    # ### end Alembic commands ###
