"""add pmp version

Revision ID: 20cd136a5b04
Revises: 2f6e36738e06
Create Date: 2025-09-22 23:59:42.724007

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "20cd136a5b04"
down_revision: Union[str, None] = "2f6e36738e06"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("pmp_climatology_dataset", schema=None) as batch_op:
        batch_op.add_column(sa.Column("version", sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("pmp_climatology_dataset", schema=None) as batch_op:
        batch_op.drop_column("version")

    # ### end Alembic commands ###
