from pathlib import Path

class Env:
    def __init__(self, expand_vars: bool) -> None: ...
    def read_env(
        self,
        path: str | None = None,
        recurse: bool = True,
        verbose: bool = False,
        override: bool = False,
    ) -> bool: ...
    def path(self, name: str, default: Path | str | None = None) -> Path: ...
    def bool(self, name: str, default: bool | None = None) -> bool: ...
    def list(self, name: str, default: list[str] | None) -> list[str]: ...
    # Ordering matters here and I don't know why
    # This `str` method must be declared last to avoid a conflict with the `str` types above
    def str(self, name: str, default: str | None = None) -> str: ...
