"""metric-values

Create the table for storing metric values

Revision ID: 765ee0fb3bae
Revises: 1f5969a92b85
Create Date: 2025-03-20 14:25:22.800249

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "765ee0fb3bae"
down_revision: Union[str, None] = "1f5969a92b85"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "metric_value",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("metric_execution_result_id", sa.Integer(), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("attributes", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )

    # This doesn't add any of the CV dimensions
    # That happens at run-time depending on which CV is used (See env.py)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("metric_value")
    # ### end Alembic commands ###
