"""migration for obs4mips

Revision ID: 7bb47d799382
Revises: 0b70f7329575
Create Date: 2025-02-27 11:34:57.642623

"""

from collections.abc import Sequence
from typing import Union

# revision identifiers, used by Alembic.
revision: str = "7bb47d799382"
down_revision: Union[str, None] = "0b70f7329575"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
